/*
 * Copyright 2019-2020 Shawn Peng
 * Email: shawnpeng@yeah.net
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.quantworld.app.constants;

public enum HbTradePairBasedOnUSDTEnum {
  actusdt,
  adausdt,
  aeusdt,
  akrousdt,
  algousdt,
  arpausdt,
  atomusdt,
  atpusdt,
  batusdt,
  bchusdt,
  bhtusdt,
  bixusdt,
  bsvusdt,
  btcusdt,
  btmusdt,
  btsusdt,
  bttusdt,
  cmtusdt,
  cnnsusdt,
  creusdt,
  crousdt,
  ctxcusdt,
  cvcusdt,
  dashusdt,
  dcrusdt,
  dogeusdt,
  dtausdt,
  egtusdt,
  ektusdt,
  elausdt,
  elfusdt,
  eosusdt,
  etcusdt,
  ethusdt,
  fsnusdt,
  fttusdt,
  gntusdt,
  gtusdt,
  gxcusdt,
  hb10usdt,
  hcusdt,
  hitusdt,
  hptusdt,
  htusdt,
  iostusdt,
  iotausdt,
  irisusdt,
  itcusdt,
  kanusdt,
  lambusdt,
  lbausdt,
  letusdt,
  linkusdt,
  lolusdt,
  ltcusdt,
  lxtusdt,
  manausdt,
  mdsusdt,
  nanousdt,
  nasusdt,
  neousdt,
  newusdt,
  nknusdt,
  nulsusdt,
  ocnusdt,
  ogousdt,
  omgusdt,
  ontusdt,
  paiusdt,
  pvtusdt,
  qtumusdt,
  rsrusdt,
  ruffusdt,
  skmusdt,
  smtusdt,
  sntusdt,
  socusdt,
  steemusdt,
  storjusdt,
  thetausdt,
  topusdt,
  trxusdt,
  ttusdt,
  uipusdt,
  uuuusdt,
  venusdt,
  vetusdt,
  vsysusdt,
  wavesusdt,
  wiccusdt,
  wtcusdt,
  wxtusdt,
  xemusdt,
  xlmusdt,
  xmrusdt,
  xrpusdt,
  xtzusdt,
  xzcusdt,
  zecusdt,
  zilusdt,
  zrxusdt;

  HbTradePairBasedOnUSDTEnum(){}

}
